### ISSUE TITLE
Neumann Region unmatched

### ISSUE THREAD

**Issue by MagicGrapix** [MeshFEM/MeshFEM#4]
Hello again !

I get an error when running a simulation on the following object.
![object](https://user-images.githubusercontent.com/38352876/103629157-450e5300-4f40-11eb-8fb5-e613187c238b.png)

The error I get is : "Neumann Region unmatched"

Now, I'm pretty new to FEM. I specified the boundary conditions as follows.

```
{
  "no_rigid_motion": false,
  "regions": [
         { "type": "dirichlet", "value": [0, 0, 0], "box%": { "minCorner": [-0.0001, -0.04, -0.04], "maxCorner": [0.401, 0.1, 1.001] } },
         { "type": "traction",  "value": [0, -0.01, 0], "box%": { "minCorner": [0.13, 0.2, 0.3], "maxCorner": [0.4, 0.4, 0.6] } }
  ]
} 
```

In my current understanding (not very mathematical), the Dirichlet boundary conditions are here to specify a state to the object and overwrite the loads that would be apply to the elements in the concerned domain. I understood it as if I was holding the object in some part in order to apply some force to it. Is that correct (even if not formal) ?

But I never specified a Neumann boundary condition, is it implicitly declared ? Why is it unmatched as the boxes I declared are intersecting with some elements of my object. Also sometimes if I get this error with forces, it disappear with traction.

Best regards !
Grapix

**Comment by jpanetta** [comment]
In the context of elasticity, a Dirichlet condition means you are prescribing a particular displacement to the selected node. In your example, all the nodes in the first box region listed will be constrained to have zero displacement; i.e., they will be stationary. A Neumann condition means you are applying some force to the region (which for the `traction` region type takes the form of a force per unit area applied to all of the boundary elements whose centroids fall within the specified region box).

This error means that none of the mesh's boundary face centroids happen to fall within the region you specified. Note that the `box%` region specifier is relative to the input model's bounding box (so specifying `"box%": { "minCorner": [0.0, 0.0, 0.0], "maxCorner": [1.0, 1.0, 1.0] }` should select the entire model's boundary).

Edit: in case it wasn't clear, both `traction` and `force` condition types are referred to as Neumann conditions in the code. I don't think switching between the two should affect this error message; the two types differ only in how the specified value is interpreted. For the `force` type, the value you specify is a total force, which is then converted to a constant traction condition by dividing by the surface area of all matched boundary elements.

**Comment by MagicGrapix** [comment]
Thanks for the quick reply. Okay, got it for Dirichlet and Neumann. But looking to my boundaries, the traction box should be intersecting with my object (which has been scaled to fit in a unit box). Isn't it ?

By looking at the axis and the values of the axis on the picture and the following box for traction
`"box%": { "minCorner": [0.13, 0.2, 0.3], "maxCorner": [0.4, 0.4, 0.6] }`
Shouldn't be the centroids from the faces located in the middle of the bank on the xz plane be selected ? I think I'm a bit confused.

Best,

**Comment by jpanetta** [comment]
It is not clear to me from the figure that the (normalized) y interval `[0.2, 0.4]` you're specifying contains the underside of the bench seat, if that's what you intend. The top side of the bench seat appears to be at (normalized) `y = 0.5`, and the underside is two cube heights below this, putting it at what looks like `y = 0.5 - 2/22 = 0.40909...`. This is not in the interval.

**Comment by MagicGrapix** [comment]
Haaa wait ! I was confused then. So you are telling that the object is not only fitting inside a bounding box but it is sheared and thus occupying the whole space (the y axis is scaled so that the object y coordinates span over `[0, 1]`) ? If indeed it is the case, my bounding box is wrong then. (just as side note I wanted to apply a force that would simulate someone sitting on the bank just to make it clear).

**Comment by jpanetta** [comment]
Yes, when using `box%`, each entry of `value` is interpreted as a fraction along the corresponding edge of the input model's bounding box. So, if you want to interpret this as a transformation of the model, then indeed it is nonuniformly scaled so that it spans the full box `[0, 1]^3`.

If you find these normalized coordinates inconvenient, you can specify absolute coordinates using `box` instead.

**Comment by MagicGrapix** [comment]
Ho okay great, I'll try this out when at home and close this issue if this was it !

**Comment by MagicGrapix** [comment]
Okay that was it, thanks for the support.
